import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {validate} from './printful-link-rest.mjs';
const plans=JSON.parse(await readFile(new URL('./printful-rest-mappings.json',import.meta.url)));
const fixture=p=>({sync_product:{external_id:p.shopifyId},sync_variants:p.mappings.map(m=>({id:m.id,external_id:m.externalId,sku:m.sku,retail_price:m.price,synced:false}))});
const catalog=p=>({product:{id:p.catalogId,model:p.model,options:[{id:'embroidery_type'},{id:'thread_colors'},{id:'thread_colors_front_large'}]},variants:p.mappings.map(m=>({id:m.variantId,product_id:p.catalogId,color:m.color,size:m.size,in_stock:true}))});
test('reject wrong external product, altered SKU, wrong color, unavailable variant, and existing conflicting mapping',()=>{const p=plans[0];validate(p,fixture(p),catalog(p));const wrong=fixture(p);wrong.sync_product.external_id='8228020977698';assert.throws(()=>validate(p,wrong,catalog(p)),/product_mismatch/);const sku=fixture(p);sku.sync_variants[0].sku='protected-existing-item';assert.throws(()=>validate(p,sku,catalog(p)),/variant_mismatch/);const color=catalog(p);color.variants[0].color='Black';assert.throws(()=>validate(p,fixture(p),color),/catalog_variant_mismatch/);const stock=catalog(p);stock.variants[0].in_stock=false;assert.throws(()=>validate(p,fixture(p),stock),/catalog_variant_mismatch/);const conflict=fixture(p);conflict.sync_variants[0].synced=true;conflict.sync_variants[0].variant_id=999;assert.throws(()=>validate(p,conflict,catalog(p)),/existing_mapping_conflict/)});
test('all 48 intended variants validate; only two approved color-specific wordmark files are assigned',()=>{assert.equal(plans.reduce((n,p)=>n+p.mappings.length,0),48);for(const p of plans)validate(p,fixture(p),catalog(p));const b=plans.find(p=>p.key==='beanie');assert.equal(b.mappings.find(m=>m.color==='Black').files[0].key,'beanie-black');assert.equal(b.mappings.find(m=>m.color==='White').files[0].key,'beanie-white');assert.notEqual(b.mappings[0].options[1].value[0],b.mappings[1].options[1].value[0])});
